import Link from 'next/link'
import Layout from '@/components/Layout/Layout'
import Head from 'next/head'
import Image from 'next/image'
import profilePic from '../../public/images/profile/developer-pic-1.png'
import AnimatedText from '@/components/Animated/AnimatedText'
import { LinkArrow } from '@/components/Icons/Icons'
import HireMe from '@/components/HireMe/HireMe'
import ligthBuld from '../../public/images/svgs/miscellaneous_icons_1.svg'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />

      </Head>
      <main className='flex items-center text-dark w-full min-h-screen dark:text-light'>
        <Layout className='pt-0'>
          <div className='flex items-center justify-between w-full'>
            <div className='w-1/2'>
              <Image src={profilePic} alt='codeblucks' className='w-full h-auto'/>
            </div>
            <div className='w-1/2 flex flex-col items-center self-center'>
              <AnimatedText text="Convertir la visión en realidad con código y diseño." className='!text-6x1 !text-left'/>
              <p className='my-4 text-base font-medium'>
              Como desarrollador full-stack experto, me dedico a convertir ideas en aplicaciones web innovadoras. 
              Explore mis últimos proyectos y artículos, mostrando mi experiencia en React.js y desarrollo web.</p>
              <div className='flex items-center self-start mt-2'>
                <Link href='/dummy.pdf' target={ "_blank"}
                className='flex items-center bg-black text-light p-2.5 px-6
                rounded-lg text-lg font-semibold hover:bg-light hover:text-dark
                border-2 border-solid border-transparent hover:border-dark
                dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light
                hover:dark:border-light'
                download={true}
                > Resume <LinkArrow className={"w-6 ml-1"}/> </Link>
                <Link href="malito:abcd@gmail.com" target={ "_blank"}
                className='flex items-center bg-yellow-500 text-light p-2.5 px-6
                rounded-lg text-lg font-semibold hover:bg-light hover:text-dark
                border-2 border-solid border-transparent hover:border-dark'
                > Contactos </Link>
                
              </div>
            </div>
          </div>
        </Layout>
        <HireMe/>
        <div className='absolute right-8 botton-8 inline-block w-24'>
          <Image src={ligthBuld} alt='codebucks' className='w-full h-auto'/>
        </div>
      </main>      
    </>
  )
}
